doug-martin/nestjs-query

- documentation/docusaurus.config.js
- documentation/src/pages/index.js
There’s not much there yet but it was even more confusing when it linked to 404s.
> Update links in docs. 

- documentation/docs/typeorm/multiple-databases.md
- documentation/sidebars.js
Dear @doug-martin ,
this PR adds a section to the docs, describing how to use this package with a multi db setup.
All the best
> [Docs]: Add Section for Multi DB Setup

- documentation/docs/graphql/federation.mdx
Updating the docs to include clearer info on how to create the necessary set up in the base type/service with `resolveReference` and `GraphQLFederationModule`.
> docs(): Update Federation Docs

- documentation/docs/introduction/example.mdx
When following the steps in the tutorial you'll be presented with this error:
```
src/todo-item/todo-item.resolver.ts:7:33 - error TS2307: Cannot find module './todo-item.service'.
7 import { TodoItemService } from './todo-item.service';
~~~~~~~~~~~~~~~~~~~~~
```
This patch removes the unused import.
> fix(docs): remove unused imports in example page

- documentation/docs/graphql/resolvers.mdx
After I transformed an auto-generated resolvers into custom CRUDResolvers with the same options, a few things stopped working.
After some debugging I found the root cause was using @Resolver without specifying the class type, like the docs are showing.
Auto-generated resolvers specify the class type here: https://github.com/doug-martin/nestjs-query/blob/master/packages/query-graphql/src/providers.ts#L112
> docs(resolvers): Add class type to custom CRUDResolver

- packages/query-graphql/__tests__/module.spec.ts
- packages/query-graphql/src/module.ts
> fix(graphql, #505): Less restrictive readResolverOpts for auto crud

- packages/query-graphql/src/module.ts
This fixes a bug to allow assemblers with overrides for the create DTO to work
> fix(graphql): Fix assemblers type for module passthrough

- packages/core/src/services/relation-query.service.ts
This changes `queryRelations`, `aggregateRelations`, `countRelations`, and `findRelation` to execute related service methods in parallel.
> feat(core): parallelize queries within relation query service

- documentation/docs/graphql/authorization.mdx
- examples/auth/e2e/todo-item.resolver.spec.ts
- examples/auth/src/sub-task/sub-task.authorizer.ts
- examples/auth/src/todo-item/dto/todo-item.dto.ts
- examples/auth/src/todo-item/todo-item.resolver.ts
- package-lock.json
- packages/query-graphql/__tests__/auth/default-crud-auth.service.spec.ts
- packages/query-graphql/src/auth/authorizer.ts
- packages/query-graphql/src/auth/default-crud.authorizer.ts
- packages/query-graphql/src/decorators/authorize-filter.decorator.ts
- packages/query-graphql/src/index.ts
- packages/query-graphql/src/resolvers/aggregate.resolver.ts
- packages/query-graphql/src/resolvers/create.resolver.ts
- packages/query-graphql/src/resolvers/delete.resolver.ts
- packages/query-graphql/src/resolvers/read.resolver.ts
- packages/query-graphql/src/resolvers/relations/aggregate-relations.resolver.ts
- packages/query-graphql/src/resolvers/relations/read-relations.resolver.ts
- packages/query-graphql/src/resolvers/relations/remove-relations.resolver.ts
- packages/query-graphql/src/resolvers/relations/update-relations.resolver.ts
- packages/query-graphql/src/resolvers/update.resolver.ts
Hey Doug,
here's a pull request that adds the primary feature requested in #1026.
I'm looking forward to your feedback.
**Contents**
- Updated `Authorizer` interface to also receive an `operationName` (optional Argument to keep backwards compatibility)
- Updated `DefaultCrudAuthorizer` and `AuthorizerOptions` to also pass along the `operationName` argument.
- Updated `AuthorizerFilter`, `RelationAuthorizerFilter` and `ModifyRelationAuthorizerFilter` to pass the name of the annotated method as `operationName` to the `Authorizer`. This name can also be overriden by a new optional argument `operationName` that was added to those decorators.
- Used this override on `queryMany` of the `ReadResolver` to change the passed name to `query` to better align with the names of the query service.
- …
> feat(graphql,auth,#1026): Pass operation name to authorizer

- documentation/docs/graphql/dtos.mdx
- examples/basic/e2e/todo-item.resolver.spec.ts
- examples/basic/src/todo-item/dto/todo-item.dto.ts
- packages/query-graphql/__tests__/decorators/filterable-fields.decorator.spec.ts
- packages/query-graphql/src/decorators/filterable-field.decorator.ts
This PR implements the `filterOnly` feature requested in #1048.
**Contents**
- Added `filterOnly` property to `FilterableFieldOptions`.
- If `filterOnly` is set to true then don't call `Field` decorator inside `@FilterableField`.
- Extended existing unit test to check that `filterOnly` is set as metadata and `Field` is not called
- Added test cases to basic example to check for absence of `filterOnly` fields and presence of those fields as filters
- Added relevant parts to documentation
> feat(graphql,#1048): added filter-only option to filterable fields

- examples/federation/graphql-gateway/src/app.module.ts
- examples/federation/todo-item-graphql/e2e/fixtures.ts
- examples/federation/todo-item-graphql/src/todo-item/dto/todo-item-input.dto.ts
- examples/federation/todo-item-graphql/src/todo-item/dto/todo-item-update.dto.ts
- examples/federation/todo-item-graphql/src/todo-item/dto/todo-item.dto.ts
- examples/federation/todo-item-graphql/src/todo-item/dto/user-reference.dto.ts
- examples/federation/user-graphql/e2e/fixtures.ts
- examples/federation/user-graphql/e2e/graphql-fragments.ts
- examples/federation/user-graphql/e2e/user.resolver.spec.ts
- examples/federation/user-graphql/src/app.module.ts
- examples/federation/user-graphql/src/main.ts
- examples/federation/user-graphql/src/user/dto/user-input.dto.ts
- examples/federation/user-graphql/src/user/dto/user-update.dto.ts
- examples/federation/user-graphql/src/user/dto/user.dto.ts
- examples/federation/user-graphql/src/user/user.entity.ts
- examples/federation/user-graphql/src/user/user.module.ts
- examples/init-scripts/mysql/init-federation.sql
- examples/init-scripts/postgres/init-federation.sql
- examples/nest-cli.json
- packages/query-graphql/src/decorators/reference.decorator.ts
- packages/query-graphql/src/resolvers/relations/references-relation.resolver.ts
This PR fixes the issue that occurs when using nullable `@Reference`. (#1051)
- omitted `keys` property from `ReferenceDecoratorOpts` (they will be merged anyways)
- Added check to see if all key fields are null and then return null for the whole reference in the resolver instead of the object containing the `__typename` and id fields set to null
- Added Users that can be assigned to TodoItems in the federation example to test nullable references.
>  fix(graphql,federation,#1051): Fix error when using nullable reference in federation

- packages/core/src/index.ts
- packages/core/src/services/index.ts
ProxyQueryService is referenced in the docs in a few [examples](https://doug-martin.github.io/nestjs-query/docs/concepts/services#proxyqueryservice) but hasn't been exported.
> Export ProxyQueryService from core

- packages/query-graphql/src/module.ts
The example from https://doug-martin.github.io/nestjs-query/docs/graphql/resolvers#crudresolver didn't work, so I thought to fix the types.
With this fix, I don't have to use this workaround:
```
NestjsQueryGraphQLModule.forFeature({
imports: [NestjsQueryTypeOrmModule.forFeature([MyThing])],
resolvers: [],
dtos: [
{
DTOClass: MyThingDRO,
CreateDTOClass: undefined as any,
UpdateDTOClass: undefined as any,
},
],
})
```
> fix: NestjsQueryGraphqlModuleOpts

- packages/query-typegoose/src/services/typegoose-query-service.ts
When trying the basic functionalities with typegoose, every GraphQL call to createOne/createMany fails with the error: `Id cannot be specified when updating or creating`.
The first place I found was [this line](https://github.com/doug-martin/nestjs-query/blob/fb6dc5455a412f16acc10c436881bf6fd139b34e/packages/query-typegoose/src/services/typegoose-query-service.ts#L239), where the error is thrown.
Then I found that the error-throwing function was called with argument `{ id: undefined }`. This weird object comes from [here](https://github.com/doug-martin/nestjs-query/blob/fb6dc5455a412f16acc10c436881bf6fd139b34e/packages/core/src/assemblers/class-transformer.assembler.ts#L53).
Hence I believe that the default behaviour is broken somehow.
There are 2 places where it can be fixed(see the 2 …
> [typegoose] default assembler for creation is unusable

- documentation/docs/persistence/mongoose/custom-service.md
docs: Service to extend in Mongoose is `MongooseQueryService`
> Fix: query service to extend in docs

- documentation/docs/introduction/example.mdx
The `Int` type for ID when using mongoose throws an error  since the mongoose `id` type is an `ObjectId()` the equivalent type in `@nestjs/graphql` would be `ID`
> docs: update id type

- documentation/docs/graphql/authorization.mdx
`InjectAuthorizer` was not imported in the docs, which made it confusing as to whether it is part of the core package or graphql package
> [docs]: import missing module

- documentation/docs/persistence/mongoose/custom-service.md
fixed a missing import `Model` from mongoos and 
typo import name for `MongooseQueryService`
> docs: fix imports in mongoose custom example

- packages/query-mongoose/README.md
remove the references to typeorm in the readme
> docs: Update mongoose package readme

- documentation/docs/graphql/authorization.mdx
- packages/query-graphql/__tests__/auth/default-crud-auth.service.spec.ts
- packages/query-graphql/src/auth/authorizer.ts
- packages/query-graphql/src/auth/default-crud.authorizer.ts
- packages/query-graphql/src/auth/tokens.ts
- packages/query-graphql/src/decorators/authorizer.decorator.ts
- packages/query-graphql/src/decorators/constants.ts
- packages/query-graphql/src/decorators/index.ts
- packages/query-graphql/src/decorators/inject-custom-authorizer.decorator.ts
- packages/query-graphql/src/index.ts
- packages/query-graphql/src/providers/authorizer.provider.ts
Should fix
#1344 
#1339 
#1336 
This is non-breaking, since the old behaviour is preserved if the default `Authorizer` interface is used.
> fix(query-graphql): Custom authorizers now behave like auth decorators

- documentation/docs/persistence/sequelize/custom-service.md
My assumption is that we should get all incomplete items and mark them as complete.
> docs() Fix typo in the code example
