doug-martin/nestjs-query

- HISTORY.md
- documentation/blog/2020-02-12-v0.2.1.md
- examples/nest-graphql-typeorm/migrations/1582064970069-add-description.ts
- examples/nest-graphql-typeorm/src/sub-task/dto/sub-task.dto.ts
- examples/nest-graphql-typeorm/src/sub-task/sub-task.entity.ts
- examples/nest-graphql-typeorm/src/todo-item/dto/todo-item.dto.ts
- examples/nest-graphql-typeorm/src/todo-item/todo-item.entity.ts
- packages/core/src/assemblers/abstract.assembler.ts
- packages/query-graphql/__tests__/decorators/fitlerable-fields.decorator.spec.ts
- packages/query-graphql/__tests__/types/query/query-args.type.spec.ts
- packages/query-graphql/src/decorators/filterable-field.decorator.ts
- packages/query-graphql/src/types/query/field-comparison/boolean-field-comparison.type.ts
- packages/query-graphql/src/types/query/field-comparison/date-field-comparision.type.ts
- packages/query-graphql/src/types/query/field-comparison/field-comparison.factory.ts
- packages/query-graphql/src/types/query/field-comparison/float-field-comparison.type.ts
- packages/query-graphql/src/types/query/field-comparison/int-field-comparison.type.ts
- packages/query-graphql/src/types/query/field-comparison/number-field-comparison.type.ts
- packages/query-graphql/src/types/query/field-comparison/string-field-comparison.type.ts
- packages/query-graphql/src/types/query/field-comparison/timestamp-field-comparison.type.ts
* Fixed case where `@FilterableField` decorator was not passing arguments correctly to `@Field` decorator #20
> Fix for issue20

- HISTORY.md
- packages/query-typeorm/__tests__/services/typeorm-query.service.spec.ts
- packages/query-typeorm/src/services/relation-query.service.ts
* [FIXED] Can't remove on Many-To-Many relations [#31]
> Fixed issue31

- HISTORY.md
- documentation/docs/graphql/resolvers.mdx
- packages/query-graphql/__tests__/decorators/resolver-method.decorator.spec.ts
- packages/query-graphql/src/decorators/resolver-method.decorator.ts
* [ADDED] `decorators` option to resolver options to allow providing custom decorators to endpoints #36
> Fix for issue36

- HISTORY.md
- documentation/docs/graphql/relations.mdx
- documentation/docs/graphql/resolvers.mdx
- packages/query-graphql/src/index.ts
- packages/query-graphql/src/resolvers/index.ts
* [DOCS] Added clarification around individual resolvers and relations with examples #42
* [ADDED] Exposed `Relatable` mixin from `@nestjs-query/graphql` #42
> Fix for issue 42

- CONTRIBUTING.md
- documentation/blog/2020-01-26-Initial Release.md
- documentation/blog/2020-01-27-v0.0.2.md
- documentation/blog/2020-01-27-v0.0.3.md
- documentation/blog/2020-01-27-v0.0.4.md
- documentation/blog/2020-01-28-v0.0.5.md
- documentation/blog/2020-01-28-v0.0.6.md
- documentation/blog/2020-02-05-v0.1.0.md
- documentation/blog/2020-02-12-v0.2.0.md
- documentation/blog/2020-02-18-v0.2.1.md
- documentation/blog/2020-02-21-v0.3.0.md
- documentation/blog/2020-02-21-v0.3.1.md
- documentation/blog/2020-02-22-v0.3.2.md
- documentation/blog/2020-02-22-v0.3.3.md
- documentation/blog/2020-02-23-v0.3.4.md
- documentation/blog/2020-02-23-v0.3.5.md
- documentation/blog/2020-02-25-v0.4.0.md
- documentation/blog/2020-02-25-v0.5.0.md
- documentation/blog/2020-03-02-v0.5.1.md
- documentation/blog/2020-03-08-v0.6.0.md
- documentation/docs/concepts/assemblers.md
- documentation/docs/concepts/dtos.md
- documentation/docs/concepts/services.md
- documentation/docs/graphql/dtos.md
- documentation/docs/introduction/getting-started.md
- documentation/docs/introduction/install.md
- documentation/docs/migration-guides/v0.5.x-to-v0.6.x.md
- documentation/docs/typeorm/getting-started.md
- documentation/docs/typeorm/usage.md
Dear @doug-martin ,
this PR only addresses some minor issues in the docs, like formatting, wrong indents, ...
I would really like to add some more docs in order to allow other people to better use this library. What do you think?
All the best,
Johannes
> [Fix] Reformat / fix typos in Docs

- HISTORY.md
- packages/query-typeorm/__tests__/services/typeorm-query.service.spec.ts
- packages/query-typeorm/src/services/typeorm-query.service.ts
* [FIXED] Issue where creating or updating allows specifying primary keys #65
> Fix for issue #65

- documentation/docs/concepts/assemblers.md
- documentation/sidebars.js
Added additional detail about services, resolvers and assemblers.
> docs(concepts): Move assemblers into the advanced section

- .run/jest.config.js.run.xml
- examples/federation/sub-task-graphql/e2e/sub-task.resolver.spec.ts
- examples/federation/tag-graphql/e2e/tag.resolver.spec.ts
- examples/federation/todo-item-graphql/e2e/todo-item.resolver.spec.ts
- examples/nest-graphql-sequelize/e2e/sub-task.resolver.spec.ts
- examples/nest-graphql-sequelize/e2e/tag.resolver.spec.ts
- examples/nest-graphql-sequelize/e2e/todo-item.resolver.spec.ts
- examples/nest-graphql-typeorm-soft-delete/e2e/todo-item.resolver.spec.ts
- examples/nest-graphql-typeorm/e2e/sub-task.resolver.spec.ts
- examples/nest-graphql-typeorm/e2e/tag.resolver.spec.ts
- examples/nest-graphql-typeorm/e2e/todo-item.resolver.spec.ts
- packages/query-graphql/__tests__/resolvers/read.resolver.spec.ts
- packages/query-graphql/__tests__/resolvers/relations/read-relation.resolver.spec.ts
- packages/query-graphql/__tests__/types/connection/connection.type.spec.ts
- packages/query-graphql/src/metadata/metadata-storage.ts
- packages/query-graphql/src/resolvers/read.resolver.ts
- packages/query-graphql/src/resolvers/relations/read-relations.resolver.ts
- packages/query-graphql/src/types/connection/connection.type.ts
- packages/query-graphql/src/types/connection/page-info.type.ts
- packages/query-graphql/src/types/connection/pager/index.ts
- packages/query-graphql/src/types/connection/pager/interfaces.ts
- packages/query-graphql/src/types/connection/pager/limit-offset.pager.ts
> fix(graphql): Fix paging to properly check next/previous page

- packages/query-typeorm/__tests__/__fixtures__/test.entity.ts
- packages/query-typeorm/__tests__/services/typeorm-query.service.spec.ts
- packages/query-typeorm/src/services/relation-query.service.ts
> fix(typeorm): Allow using string based typeorm relations

- packages/query-typeorm/src/services/typeorm-query.service.ts
> fix(typeorm): Ensure record is entity instance when saving

- documentation/docs/graphql/hooks.mdx
- documentation/sidebars.js
- examples/typeorm/e2e/tag.resolver.spec.ts
- examples/typeorm/e2e/todo-item.resolver.spec.ts
- examples/typeorm/src/constants.ts
- examples/typeorm/src/helpers.ts
- examples/typeorm/src/sub-task/dto/sub-task.dto.ts
- examples/typeorm/src/sub-task/dto/subtask-input.dto.ts
- examples/typeorm/src/sub-task/dto/subtask-update.dto.ts
- examples/typeorm/src/sub-task/sub-task.entity.ts
- examples/typeorm/src/tag/dto/tag.dto.ts
- examples/typeorm/src/tag/tag.entity.ts
- examples/typeorm/src/todo-item/dto/todo-item-input.dto.ts
- examples/typeorm/src/todo-item/dto/todo-item-update.dto.ts
- examples/typeorm/src/todo-item/dto/todo-item.dto.ts
- examples/typeorm/src/todo-item/todo-item.entity.ts
- packages/query-graphql/src/decorators/constants.ts
- packages/query-graphql/src/decorators/decorator.utils.ts
- packages/query-graphql/src/decorators/hook.decorator.ts
- packages/query-graphql/src/decorators/index.ts
- packages/query-graphql/src/decorators/mutation-args.decorator.ts
- packages/query-graphql/src/decorators/skip-if.decorator.ts
- packages/query-graphql/src/index.ts
- packages/query-graphql/src/resolvers/create.resolver.ts
- packages/query-graphql/src/resolvers/delete.resolver.ts
- packages/query-graphql/src/resolvers/helpers.ts
- packages/query-graphql/src/resolvers/update.resolver.ts
> feat(hooks): Add hooks for mutations

- documentation/docs/graphql/hooks.mdx
- packages/query-graphql/package.json
- packages/query-graphql/src/decorators/aggregate-query-param.decorator.ts
>  fix(graphql,aggregations): Exclude __typename in aggregations

- packages/query-graphql/__tests__/metadata/metadata-storage.spec.ts
- packages/query-graphql/src/metadata/metadata-storage.ts
> fix(graphql): Include inherited references and relations

- documentation/docs/graphql/dtos.md
- documentation/docs/utilities/query-helpers.mdx
- documentation/docusaurus.config.js
- packages/core/src/helpers/filter.builder.ts
- packages/core/src/interfaces/filter-field-comparison.interface.ts
- packages/query-graphql/__tests__/__fixtures__/filter-allowed-comparisons-input-type.graphql
- packages/query-graphql/__tests__/__fixtures__/index.ts
- packages/query-graphql/__tests__/types/query/filter.type.spec.ts
- packages/query-graphql/src/decorators/filterable-field.decorator.ts
- packages/query-graphql/src/decorators/index.ts
- packages/query-graphql/src/index.ts
- packages/query-graphql/src/metadata/metadata-storage.ts
- packages/query-graphql/src/types/aggregate/aggregate-response.type.ts
- packages/query-graphql/src/types/query/field-comparison/field-comparison.factory.ts
- packages/query-graphql/src/types/query/filter.type.ts
- packages/query-sequelize/src/query/where.builder.ts
- packages/query-typeorm/src/query/where.builder.ts
>  feat(graphql): Allow specifying allowed comparisons on filterable fields

- documentation/docs/graphql/dtos.md
- packages/query-graphql/__tests__/__fixtures__/cursor-query-args-required-filter-type.graphql
- packages/query-graphql/__tests__/__fixtures__/filter-required-field-input-type.graphql
- packages/query-graphql/__tests__/__fixtures__/index.ts
- packages/query-graphql/__tests__/__fixtures__/no-paging-query-args-required-filter-type.graphql
- packages/query-graphql/__tests__/__fixtures__/offset-query-args-required-filter-type.graphql
- packages/query-graphql/__tests__/types/query/filter.type.spec.ts
- packages/query-graphql/__tests__/types/query/query-args.type.spec.ts
- packages/query-graphql/src/decorators/filterable-field.decorator.ts
- packages/query-graphql/src/metadata/metadata-storage.ts
- packages/query-graphql/src/types/query/filter.type.ts
- packages/query-graphql/src/types/query/query-args/cursor-query-args.type.ts
- packages/query-graphql/src/types/query/query-args/no-paging-query-args.type.ts
- packages/query-graphql/src/types/query/query-args/offset-query-args.type.ts
>  feat(graphql): Allow specifying fields that are required when querying

- packages/query-typeorm/.eslintrc.js
- packages/query-typeorm/__tests__/__fixtures__/seeds.ts
- packages/query-typeorm/__tests__/__fixtures__/test-relation.entity.ts
- packages/query-typeorm/__tests__/__fixtures__/test.entity.ts
- packages/query-typeorm/__tests__/query/relation-query.builder.spec.ts
- packages/query-typeorm/__tests__/services/typeorm-query.service.spec.ts
- packages/query-typeorm/src/query/relation-query.builder.ts
> fix(typeorm,#493): Fix uni-directional relation SQL

- packages/core/src/common/reflect.utils.ts
- packages/query-graphql/__tests__/decorators/hook.decorator.spec.ts
- packages/query-graphql/src/decorators/hook.decorator.ts
> fix(graphql,hooks): Allow getting hooks from parent classes

- packages/query-typeorm/__tests__/query/sql-comparison.builder.spec.ts
- packages/query-typeorm/package.json
- packages/query-typeorm/src/common/index.ts
- packages/query-typeorm/src/common/randomString.ts
- packages/query-typeorm/src/query/sql-comparison.builder.ts
Fix issue with incorrect SQL script parameters when, filtering 2 relationships, using typeorm.
https://github.com/doug-martin/nestjs-query/issues/562
> fix(filters): Fix bug with incorect parameters in filters

- documentation/docs/utilities/query-helpers.mdx
- packages/core/__tests__/helpers.spec.ts
- packages/core/src/helpers/comparison.builder.ts
- packages/core/src/helpers/filter.builder.ts
- packages/core/src/helpers/filter.helpers.ts
- packages/core/src/helpers/index.ts
- packages/core/src/helpers/query.helpers.ts
- packages/core/src/index.ts
This adds two new filter helpers: `getFilterComparisons` and `getFilterOmitting`. We've also shuffled some methods into a new file `filter.helpers.ts` for better organization.
> feat(core): added two new filter helpers

- documentation/docs/persistence/typeorm/service-testing.md
I had some troubles to test my services that extend `TypeOrmQueryService`. After having found a solution I decided to create some doc.
Note, I'm not a native speaker, so the language can be rough in some points. Feel free to improve/correct.
> docs: Add doc for testing services with typeorm

- documentation/docs/graphql/authorization.mdx
> Typo fixed in Authorization docs.

- documentation/docs/graphql/hooks.mdx
> Fixed typo in hooks doc

- documentation/docs/introduction/example.mdx
Fix missing import statement in todo-item.module.ts (mongoose example)
> docs: fix missing import

- packages/query-typeorm/__tests__/query/where.builder.spec.ts
- packages/query-typeorm/src/query/where.builder.ts
* This ensures that groupings are correct
> fix(typeorm,#895): Wrap all OR and AND expressions in brackets

- documentation/docs/graphql/resolvers.mdx
> docs(graphql): Add warning to always use Resolver(() => DTOClass)

- .github/ISSUE_TEMPLATE/---bug-report.md
Fixes a typo in the bug issue template:
~Node Verson~
Node Version
> chore(bug-template): Fix typo in node version

- documentation/docs/persistence/typegoose/relations.mdx
the example contained a deprecated typegoose example within it and had wrong lines highlighted
> fix: fix highlight and duplicate example

- documentation/docs/persistence/mongoose/custom-service.md
- packages/query-graphql/src/types/connection/array-connection.type.ts
- packages/query-graphql/src/types/connection/cursor/cursor-connection.type.ts
- packages/query-graphql/src/types/connection/cursor/pager/pager.ts
- packages/query-graphql/src/types/connection/cursor/pager/strategies/keyset.pager-strategy.ts
- packages/query-graphql/src/types/connection/cursor/pager/strategies/limit-offset.pager-strategy.ts
- packages/query-graphql/src/types/connection/cursor/pager/strategies/pager-strategy.ts
- packages/query-graphql/src/types/connection/interfaces.ts
- packages/query-graphql/src/types/connection/offset/offset-connection.type.ts
- packages/query-graphql/src/types/connection/offset/pager/pager.ts
- packages/query-mongoose/README.md
* Changes from #1255 
* Update types to support custom query type.
> feat(query-graphql): pass original query in keyset pager strategy

- documentation/docs/graphql/hooks.mdx
createdBy should be updatedBy.
> Correct verbiage

- jest.e2e.config.js
- jest.unit.config.js
- packages/query-typeorm/__tests__/__fixtures__/connection.fixture.ts
- packages/query-typeorm/__tests__/__fixtures__/relation-of-test-relation.entity.ts
- packages/query-typeorm/__tests__/__fixtures__/seeds.ts
- packages/query-typeorm/__tests__/__fixtures__/test-relation.entity.ts
- packages/query-typeorm/__tests__/__fixtures__/test.entity.ts
- packages/query-typeorm/__tests__/query/__snapshots__/relation-query.builder.spec.ts.snap
- packages/query-typeorm/__tests__/query/filter-query.builder.spec.ts
- packages/query-typeorm/__tests__/query/where.builder.spec.ts
- packages/query-typeorm/__tests__/services/typeorm-query.service.spec.ts
- packages/query-typeorm/package.json
- packages/query-typeorm/src/query/filter-query.builder.ts
- packages/query-typeorm/src/query/relation-query.builder.ts
- packages/query-typeorm/src/query/where.builder.ts
- tsconfig.build.json
> feat(query-typeorm): allow deeply nested filters

- documentation/docs/graphql/dtos.mdx
- documentation/docs/graphql/paging.mdx
- documentation/docs/persistence/typeorm/testing-services.md
Minor wording changes, nothing to comment really
> Minor code examples and wording corrections in docs
